// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxqPmExh6n5EC2KjwhkDsnqpCC6VXGw8g',
    appId: '1:370713648945:web:dfb87bf60dc2401b3d5a10',
    messagingSenderId: '370713648945',
    projectId: 'movie-app-418b8',
    authDomain: 'movie-app-418b8.firebaseapp.com',
    storageBucket: 'movie-app-418b8.firebasestorage.app',
    measurementId: 'G-TV08NE5K2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7RnDFWH5F0yoMLa2ahvJC9L_5tliGQA0',
    appId: '1:370713648945:android:cabd77be7fad29b03d5a10',
    messagingSenderId: '370713648945',
    projectId: 'movie-app-418b8',
    storageBucket: 'movie-app-418b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeugK3JCywB26KmUOtSbdNZcFE8sZOk8',
    appId: '1:370713648945:ios:7ec66c5a7d8a3c7d3d5a10',
    messagingSenderId: '370713648945',
    projectId: 'movie-app-418b8',
    storageBucket: 'movie-app-418b8.firebasestorage.app',
    iosBundleId: 'com.shahd.dev.movieapp.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUeugK3JCywB26KmUOtSbdNZcFE8sZOk8',
    appId: '1:370713648945:ios:7ec66c5a7d8a3c7d3d5a10',
    messagingSenderId: '370713648945',
    projectId: 'movie-app-418b8',
    storageBucket: 'movie-app-418b8.firebasestorage.app',
    iosBundleId: 'com.shahd.dev.movieapp.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxqPmExh6n5EC2KjwhkDsnqpCC6VXGw8g',
    appId: '1:370713648945:web:c33785300eb8d81b3d5a10',
    messagingSenderId: '370713648945',
    projectId: 'movie-app-418b8',
    authDomain: 'movie-app-418b8.firebaseapp.com',
    storageBucket: 'movie-app-418b8.firebasestorage.app',
    measurementId: 'G-L8M6941JCH',
  );
}
